name: Check Artifact Size
description: Whether to check artifact binary size
inputs:
  threshold:
    description: "Threshold for artifact binary size increase."
    required: true
  path:
    description: "Path to the artifact being checked."
    required: true
runs:
  using: "composite"
  steps:
      - name: Get size of libcobalt.so
        # The `download-artifact` action can only access artifacts that were uploaded in the same workflow.
        # Since it was not this workflow that uploaded the artifacts we must use rest api to download them.
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
        uses: actions/github-script@v6
        with:
          script: |
            let workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'evergreen.yaml',
              branch: 'main',
              status: 'success',
              per_page: 1
            });

            console.log(JSON.stringify(workflowRuns, null, 2));

            let latestRun = workflowRuns.data.workflow_runs[0].id;

            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: latestRun
            });

            let matchArtifacts = allArtifacts.data.artifacts.filter((artifact) => {
              console.log(`artifact: ${artifact}`);
              return artifact.name == "libcobalt.so";
            });

            if (matchArtifacts.length == 1) {
              let cur_size = matchArtifacts[0].size_in_bytes;
              console.log(`size: ${cur_size}`);
              console.log(`new_size: ${inputs.path.size}`);
              if (new_size - cur_size > inputs.threshold) {
                core.setFailed(`Artifact size increase over threshold`);
              }
            } else {
              core.setFailed(`Expected one artifact with name 'libcobalt.so'. Found ${matchArtifacts.length}.`);
            }
